### ISSUE TITLE
重连方法导致重复消息发送

### ISSUE THREAD

**Issue by aion1998** [2881099/im#12]
如果IM服务端断了，前端会启动一个3s一次的请求去拿token，然后尝试重新链接。

虽然最后是可以重新链接上，但是这时候发送信息就会有发生重复

调了半天好像是Acceptor这里拿有效token的时候，因为是异步的而我每3秒来拿，所以会拿好多好多有效的。

有没有啥好的解决方法？

**Comment by 2881099** [comment]
gettoken 那里限制下，每个用户你好可以产生一个 token
