### ISSUE TITLE
关于.net web api nancy 的项目如何引用呢？

### ISSUE THREAD

**Issue by lauralxj** [2881099/im#21]
现在有个webapi nancy 的项目 .net 4.5,想把这个项目用在上面，如何使用呢？这问题问的我自己都不好意思，拜托有空指点一下，谢谢！

**Comment by 2881099** [comment]
nuget 下载到你的 net 4.5 项目中直接使用。

另外要单独部署imserver netcoreapp 程序，以及他所需的 redis-server 环境。

你的 net 4.5 程序和 imserver 是分开部署的，imserver 不需要维护更新迭代开发。他们之间通过 nuget 上的组件进行通讯。

比如你的项目中使用 ImHelper.SendMessage

**Comment by lauralxj** [comment]
> 另外要单独部署imserver netcoreapp 程序，以及他所需的 redis-server 环境
是指ImCore 项目吗？我看着是个类库项目，请问怎么部署，谢谢！

**Comment by 2881099** [comment]
看源码里面的 demo

**Comment by lauralxj** [comment]
谢谢！
