### ISSUE TITLE
关于wss 协议的发布

### ISSUE THREAD

**Issue by lauralxj** [2881099/im#22]
目前看到是ws 的，如果单独部署imserver , 如何配置证书呢？示例代码中不支持下图参数
[网络图片](https://img-blog.csdnimg.cn/20190128160011526.png)
期待回复，谢谢！

**Comment by 2881099** [comment]
https://github.com/2881099/im/issues/11

**Comment by 2881099** [comment]
https://github.com/2881099/im/issues/3

**Comment by 2881099** [comment]
wss 他 imcore im 没有绑定关系，wss 参考 https aspnetcore 配置的教程就好了。

**Comment by lauralxj** [comment]
谢谢回复
现在的场景如下：
1.终端是小程序
2.web api 是.net framework 4.5
3.按照昨天您提示的我发布了ImServer.exe 
4.IP连接没有问题，ImServer.exe 这怎么绑定域名啊，感谢

**Comment by 2881099** [comment]
ImServer.exe 这怎么绑定域名

```csharp
    public class Program
    {
        public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseKestrel(option=> {
                    option.UseHttps("server.pfx", "linezero");
                })
                .UseUrls("https://www.baidu.com:443")
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();

            host.Run();
        }
    }
```

**Comment by 2881099** [comment]
websocket 不限制端口号，小程序可以用 wss://www.baidu.com:6001 连接

**Comment by 2881099** [comment]
.UseKestrel(option=> {
                    option.UseHttps("server.pfx", "linezero");
                })
                .UseUrls("https://www.baidu.com:443")

这两个配置是关键，其他资料可以到百度搜索：aspnetcore https 配置

**Comment by lauralxj** [comment]
可以理解为把ImServer下的Program文件增加

> .UseKestrel(option=> {

                option.UseHttps("server.pfx", "linezero");
            })
            .UseUrls("https://www.baidu.com:443")'
如上代码，ImServer可以部署在iis上，由iIS承载吗？

**Comment by 2881099** [comment]
不用挂载，独立运行

**Comment by lauralxj** [comment]
搞不定，崩溃：

> Startup.cs
`app.UseImServer(new ImServerOptions
            {
                Redis = new CSRedis.CSRedisClient("127.0.0.1:6379,poolsize=5"),
                Servers = new[] { "39.243.73.68:8080" },
                Server = "39.243.73.68:8080"
            });`

> Program.cs
`WebHost.CreateDefaultBuilder(args)
                 .UseKestrel(options =>
                    {
                        options.Listen(IPAddress.Loopback, 8080, listenOptions =>
                        {
                            listenOptions.UseHttps("message.pfx", "9874321");
                        });
                    })
                 .UseUrls("https://www.baidu.com:8080")
                 .UseStartup<Startup>();`
`public string PrevConnectServer(Guid clientId, string clientMetaData)
    {
        var server = SelectServer(clientId);
        var token = $"{Guid.NewGuid()}{Guid.NewGuid()}{Guid.NewGuid()}{Guid.NewGuid()}".Replace("-", "");
        _redis.Set($"{_redisPrefix}Token{token}", JsonConvert.SerializeObject((clientId, clientMetaData)), 10);
        return $"wss://{server}{_pathMatch}?token={token}";
    }`
结果报错如下：

> 以一种权限不允许的方式做了一个访问套接字的尝试
网上说是端口占用的问题，更改后依然报此错误。
期待帮助，谢谢！

**Comment by 2881099** [comment]
实在弄不好的话，就用 http 转发吧，把其他 https 的服务器转发给这里。就不用在这里配置 ssl 了

**Comment by lauralxj** [comment]
方便留个交流方式或者建个群不，付费指导也行啊，发了二天时间了搞不定。
QQ：18477899

**Comment by 2881099** [comment]
> 方便留个交流方式或者建个群不，付费指导也行啊，发了二天时间了搞不定,今天才发现API获取ws url后根本连接不上。
> QQ：18477899

 加你了，等通过

**Comment by lauralxj** [comment]
结贴，在作者的远程指导下终于连线成功，抽时间整理一下发出来，避免其它使用者再走弯路，感谢！
