### ISSUE TITLE
引入Nuget包和直接拉源码，链接WebSocket问题

### ISSUE THREAD

**Issue by YCSiTong** [2881099/im#23]
您好，我自己在之前使用Nuget包的时候，正常的一个使用没问题的，但是我从git上拉您的源码下来使用后，我前端链接Websocket时，后端就会说资源以释放，不可访问.想请教一下是需要哪里配置吗.

**Comment by 2881099** [comment]
是一样呢，具体是什么错误

**Comment by YCSiTong** [comment]
System.ObjectDisposedException:“Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.

**Comment by 2881099** [comment]
这个是注入问题，被释放了，检查注入方式

**Comment by YCSiTong** [comment]
可是您的这个不是直接写中间件就好了吗，是要把那三个文件都单例注入是吗

**Comment by 2881099** [comment]
按照demo来

**Comment by YCSiTong** [comment]
我找到问题了,因为我在您的事件总线 里面加入了两个事件,我需要在用户上线下线的时候执行对应的一些业务处理,谢谢您

**Comment by YCSiTong** [comment]
请问您有一个qq群之类的吗

**Comment by 2881099** [comment]
只开了freesql orm群，其他开源库没有qq群
