### ISSUE TITLE
您好，测试报如下图错误，所有配置都配好了，这是什么原因？

### ISSUE THREAD

**Issue by huffhu** [2881099/im#30]
![image](https://user-images.githubusercontent.com/30171884/102735380-4571f000-437d-11eb-924f-131e78f6b713.png)

**Comment by 2881099** [comment]
发一下文字信息，手机没有翻墙

**Comment by huffhu** [comment]
WebSocket connection to 'ws://127.0.0.1:6001/ws?token=dbd936ed18734205b489f700b5a3476bb7ab8f94dd3b42c4b966f79c35a4222c1eaacaf6b1bf4c43b6700dcbfd8df3dd0a4e9f0519414d96b85fb26a2f5a78d5' failed: Error during WebSocket handshake: Unexpected response code: 200

**Comment by 2881099** [comment]
redis 配置一样吗

**Comment by huffhu** [comment]
一样的
"ImServerOption": {
    "RedisClient": "127.0.0.1:6379,poolsize=10",
    "Servers": "127.0.0.1:6001",
    "Server": "127.0.0.1:6001"
  }

**Comment by huffhu** [comment]
webapi配置
ImHelper.Initialization(new ImClientOptions
            {
                Redis = new FreeRedis.RedisClient("127.0.0.1:6379,poolsize=10"),
                Servers = new[] { "127.0.0.1:6001" }
            });

**Comment by 2881099** [comment]
imserver 启动端口是多少

—urls=http://*:6001

**Comment by huffhu** [comment]
启动端口6001

**Comment by huffhu** [comment]
你好，大佬，用户离开监听不到，知道什么原因吗？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "2881099"<notifications@github.com&gt;; 
发送时间: 2020年12月21日(星期一) 中午11:19
收件人: "2881099/im"<im@noreply.github.com&gt;; 
抄送: "陌雨轩"<1012914472@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [2881099/im] 您好，测试报如下图错误，所有配置都配好了，这是什么原因？ (#30)





 
imserver 启动端口是多少
 
—urls=http://*:6001
