### ISSUE TITLE
在https方式下收不到消息

### ISSUE THREAD

**Issue by kuiyu** [2881099/im#46]
我有两个应用一个使用http 一个使用https 两个应用的用户socketId相同
http使用ws, https 方式连接wss，两个应用都可以正常连接imServer
http一切正常，
当使用https的应用时，连接服务器正常，就是收不到消息
此时，同时把http的应用浏览器打开并连接im，https的应用就可以正常收到消息了;如果把http应用连接关闭，就收不到消息
这是什么原因？期待回复

**Comment by 2881099** [comment]
如果 wss 单独设置 socketid 呢

**Comment by kuiyu** [comment]
谢谢 ，可以了
